platform :ios, '8.0'

inhibit_all_warnings!

target 'LindaNetwork_Example' do
  pod 'LindaNetwork', :path => '../'
  pod 'YYModel'
  pod 'YYCache'
  
  target 'LindaNetwork_Tests' do
    inherit! :search_paths

    
  end
end
